### ISSUE TITLE
This is a DBAL, not DAL

### ISSUE THREAD

**Issue by Yousha** [corsac-dart/stateless#2]
**DBAL = DataBase Abstraction Layer**
https://en.wikipedia.org/wiki/Database_abstraction_layer

>  **Database abstraction layer** is an application programming interface which unifies the communication between a computer application and databases such as SQL Server, DB2, MySQL, PostgreSQL, Oracle or SQLite.

**DAL = Data Access Layer**
https://en.wikipedia.org/wiki/Data_access_layer

> **Data access layer** (DAL) in computer software, is a layer of a computer program which provides simplified access to data stored in persistent storage of some kind, such as an entity-relational database.

**Comment by pulyaevskiy** [comment]
Thanks! Curious what makes you think that this library is a DBAL?

My understanding of DBAL is that it unifies communication interface across multiple databases, so a typical DBAL implementation for RDBM systems would have an abstraction around establishing connections, some configuration and a generic QueryBuilder based on SQL semantics where you would have methods like `select`, `insert`, `where` and such.

This library's goal is to stay away from those details and instead focus on domain level of an application. That's why it implements `Repository` pattern in a very generic/opinionated way.

I named it `DAL` because it's a broader concept which does not imply any specific implementation.

P.S.: I should warn that I'm not working on this or any other `corsac-*` libraries at the moment, and not sure when I'll be able to get back to it. This is an experimental project and things can and most likely drastically change in future.

**Comment by Yousha** [comment]
Hmm, so I think you should change the project's Description to: **Data access layer**
Instead of Database abstraction layer

**Comment by pulyaevskiy** [comment]
Haha, good point! Thanks, updated.
